[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.1"

# The title and description fields are primarily for displaying extension info in UI
title = "Camera View Optimizer"
description="Omniverse extensions that allow you to quickly hide/delete objects that are not visible to the camera to save performance and VRAM."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = "https://github.com/Vadim-Karpenko/omniverse-camera-view-optimizer"

# One of categories for UI.
category = "Lighting & Rendering"

# Keywords for the extension
keywords = ["camera", "view", "optimizer", "optimization", "performance", "vram", "memory", "hide", "delete", "visibility", "culling"]

authors = ["Vadim Karpenko"]

icon = "data/icon.png"

preview_image = "data/preview_image.png"

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides, it will be publicly available as "import karpenko.camera_view_optimizer.ext".
[[python.module]]
name = "karpenko.camera_view_optimizer.ext"

[[python.module]]
name = "karpenko.camera_view_optimizer.ext.commands"
